export default function Head() {
  return (
    <div>
      <title>Barcode Factory</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
    </div>
  )
}
