import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Layout from '../components/layout'

function Home() {
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.container}>
      </main>
    </Layout>
  )
}

export default Home
