import Head from 'next/head';
import styles from '../styles/qrcode.module.css';
import Layout from '../components/layout';
import React, { useEffect, useState } from "react";
import Router from 'next/router';

function Home() {
  const [loaded, setLoaded] = useState(false);

  useEffect(() => {
    const { pathname } = Router;

    if (pathname == '/') {
      Router.push('/qrcode/create');
    }
    else {
      setLoaded(true);
    }
  }, []);

  if (!loaded) {
    return <div></div>
  }

  return (
    <Layout>
      <Head>
        <title>Barcode Factory</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.container}></main>
    </Layout>
  )
}

export default Home
