import Head from 'next/head'
import styles from '../../styles/qrcode.module.css'
import Layout from '../../components/layout'
import Link from 'next/link'

export default function QRCode() {
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.container}>
        <div className={styles.gridTable}>
          <Link href='/qrcode/create/website'>
            <a className={styles.gridRow}>
              <div className={styles.innerRow}>
                <div className={styles.title}>
                  Website URL QR Code
                </div>
                <div className={styles.description}>When scanned, redirects user to a website</div>
              </div>
            </a>
          </Link>
          <Link href='/qrcode/create/number'>
            <a className={styles.gridRow}>
              <div className={styles.innerRow}>
                <div className={styles.title}>
                  Phone Number QR Code
                </div>
                <div className={styles.description}>When scanned, displays the option to call to that number</div>
              </div>
            </a>
          </Link>
          <Link href='/qrcode/create/map'>
            <a className={styles.gridRow}>
              <div className={styles.innerRow}>
                <div className={styles.title}>
                  Google Maps QR Code
                </div>
                <div className={styles.description}>When scanned, displays location on map</div>
              </div>
            </a>
          </Link>
        </div>
      </main>
    </Layout>
  )
}
